<?php
/**
 * @file
 * Drupal needs this blank file.
 */

// Import differents '.component.inc' files (as Atomium theme) from templates/.
$directory = new RecursiveDirectoryIterator(__DIR__ . '/templates/');
$iterator = new RecursiveIteratorIterator($directory);
$regex = new RegexIterator($iterator, '/^.+\.component.inc$/i', RecursiveRegexIterator::GET_MATCH);
foreach ($regex as $name => $regex) {
  include $name;
}

/**
 * Implements hook_theme().
 */
function header_footer_corporate_theme() {
  return array(
    'header__ec_corporate' => array(
      'template' => 'header--ec-corporate',
    ),
    'footer__ec_corporate' => array(
      'template' => 'footer--ec-corporate',
    ),
    'links__ecl_menus' => array(
      'file' => 'includes/links__ecl_menus.theme.inc',
      'function' => '_header_footer_corporate_theme_links__ecl_menus',
      'arguments' => array(
        'variables' => array(
          'links' => array(
            'href',
            'language',
          ),
          'attributes' => array(
            'id',
            'class',
          ),
          'heading' => array(
            'class',
          ),
        ),
      ),
    ),
  );
}

/**
 * Implements hook_theme_registry_alter().
 */
function header_footer_corporate_theme_registry_alter(&$theme_registry) {
  // ################
  // Add templates in custom modules :
  // Source : https://www.drupal.org/docs/7/creating-custom-modules/howtos/using-template-tplphp-files-in-your-own-module.
  // Defined path to the current module.
  $module_path = drupal_get_path('module', 'header_footer_corporate');
  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }

  // ################
  // Redefine the theme_button() function.
  $theme_registry['button']['function'] = '_header_footer_corporate_theme_button';
  $theme_registry['button']['includes'] = array($module_path . '/includes/button.theme.inc');
  // Redefine the theme_easy_breadcrumb() from easy_breadcrumb.module.
  $theme_registry['easy_breadcrumb']['function'] = '_header_footer_corporate_theme_easy_breadcrumb';
  $theme_registry['easy_breadcrumb']['includes'] = array($module_path . '/includes/easy_breadcrumb.theme.inc');
}

/**
 * Implenents hook_form_FORM_ID_alter().
 */
function header_footer_corporate_form_nexteuropa_europa_search_search_form_alter(&$form, &$form_state, $form_id) {
  $form['search_input_group']['QueryText']['#attributes']['placeholder'] = '';
  $form['search_input_group']['europa_search_submit']['#value'] = t('Search', array(), array('context' => 'nexteuropa_search_form:button'));

  unset($form['search_input_group']['QueryText']['#title']);
  unset($form['search_input_group']['QueryText']['#attributes']);
  $form['search_input_group']['QueryText']['#attributes']['class'] = array('ecl-text-input', 'ecl-search-form__textfield');
  $form['search_input_group']['QueryText']['#attributes']['size'] = '10';
  $form['search_input_group']['#prefix'] = '';
  $form['search_input_group']['#suffix'] = '';
  $form['search_input_group']['europa_search_submit']['#type'] = 'submit';
  $form['search_input_group']['europa_search_submit']['#ecl-buttontype'] = 'button';
  $form['#attributes']['class'][0] = 'ecl-search-form';
  $form['#attributes']['class'][1] = 'ecl-site-header__search';
}

/**
 * Implements hook_context_load_alter().
 */
function header_footer_corporate_context_load_alter(&$context) {
  // Remove breadcrumb and footer setted by platform.
  if ($context->name === 'site_wide') {
    if (isset($context->reactions['block']['blocks']['easy_breadcrumb-easy_breadcrumb'])) {
      unset($context->reactions['block']['blocks']['easy_breadcrumb-easy_breadcrumb']);
    }

    if (isset($context->reactions['block']['blocks']['footer']) &&
    $context->reactions['block']['blocks']['footer']['delta'] == 'footer_ipg') {
      unset($context->reactions['block']['blocks']['footer']);
    }
  }
}

/**
 * Implements hook_preprocess().
 */
function header_footer_corporate_preprocess(&$variables, $hook) {
  switch($hook){
    case 'page':
    case 'maintenance_page':
    
      if (!path_is_admin(current_path())) {
        // Adding CSS and JS files.
        $path_module = drupal_get_path('module', 'header_footer_corporate');
        drupal_add_js($path_module . '/assets/europa/scripts/europa.min.js',
          array(
            'type' => 'file',
            'scope' => 'footer',
            'group' => JS_THEME,
          ));
        drupal_add_css($path_module . '/assets/europa/styles/europa.min.css',
          array(
            'group' => 300, // more than CSS_THEME (=100) to not be overrided.
            'weight' => 100,
          ));
        drupal_add_css($path_module . '/css/header_footer_corporate.css',
          array(
            'group' => 300, // more than CSS_THEME (=100) to not be overrided.
            'weight' => 101,
            'cache' => FALSE,
          ));
    
        // Define custom variables to be used in .tpl files.
        $variables['header__ec_corporate'] = theme('header__ec_corporate', array(
          'site_name' => $variables['site_name'],
        ));
        $variables['footer__ec_corporate'] = theme('footer__ec_corporate', array(
          'site_name' => $variables['site_name'],
        ));
      }
      break;
  }
}