<?php

/**
 * @file
 * Drupal needs this blank file.
 */

use HeaderFooter\HeaderFooterHelpers;

include_once 'header_footer.helpers.inc';

// Import differents '.component.inc' files (as Atomium theme) from templates/.
$directory = new RecursiveDirectoryIterator(__DIR__ . '/templates/');
$iterator = new RecursiveIteratorIterator($directory);
$regex = new RegexIterator($iterator, '/^.+\.component.inc$/i', RecursiveRegexIterator::GET_MATCH);
foreach ($regex as $name => $regex) {
  include $name;
}

/**
 * Implements hook_theme().
 */
function header_footer_theme() {
  return array(
    'header_ec' => array(
      'template' => 'header-ec',
    ),
    'footer_ec' => array(
      'template' => 'footer-ec',
    ),
    'breadcrumb_ec' => array(
      'template' => 'breadcrumb-ec',
    ),
    'menu_items_ec_lists' => array(
      'file' => 'themes/menu_items_ec_lists.theme.inc',
      'arguments' => array(
        'variables' => array(
          'links' => array(
            'href',
            'language',
          ),
          'attributes' => array(
            'id',
            'class',
          ),
          'heading' => array(
            'class',
          ),
        ),
      ),
    ),
    'menu_items_ec_links' => array(
      'template' => 'menu-items-ec-links',
      'arguments' => array(
        'variables' => array(
          'links' => array(
            'href',
            'language',
          ),
          'attributes' => array(
            'id',
            'class',
          ),
          'heading' => array(
            'class',
            'level',
            'text',
          ),
        ),
      ),
    ),
  );
}

/**
 * Implements hook_theme_registry_alter().
 */
function header_footer_theme_registry_alter(&$theme_registry) {
  // ################
  // Add templates in custom modules :
  // Source : https://www.drupal.org/docs/7/creating-custom-modules/howtos/using-template-tplphp-files-in-your-own-module.
  // Defined path to the current module.
  $module_path = drupal_get_path('module', 'header_footer');
  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }

  // ################
  // Redefine the theme_button() function.
  $theme_registry['button']['function'] = '_header_footer_theme_button';
  $theme_registry['button']['includes'] = array($module_path . '/themes/button.theme.inc');
  // Redefine the theme_easy_breadcrumb() from easy_breadcrumb.module.
  $theme_registry['easy_breadcrumb']['function'] = '_header_footer_theme_breadcrumb';
  $theme_registry['easy_breadcrumb']['includes'] = array($module_path . '/themes/easy_breadcrumb.theme.inc');
}

/**
 * Implenents hook_form_FORM_ID_alter().
 */
function header_footer_form__easy_breadcrumb_general_settings_form_alter(&$form, &$form_state, $form_id) {
  $form['easy_breadcrumb']['#description'] = t('<i>Some settings had been removed by <b>Header Footer</b> module because it is not used in the breadcrumb.</i>');
  $form['easy_breadcrumb']['easy_breadcrumb-disable_drupal_breadcrumb']['#access'] = FALSE;
  $form['easy_breadcrumb']['easy_breadcrumb-include_title_segment']['#access'] = FALSE;
  $form['easy_breadcrumb']['easy_breadcrumb-title_from_page_when_available']['#access'] = FALSE;
  $form['easy_breadcrumb']['easy_breadcrumb-title_segment_as_link']['#access'] = FALSE;
  $form['easy_breadcrumb']['easy_breadcrumb-capitalizator_mode']['#access'] = FALSE;
  $form['easy_breadcrumb']['easy_breadcrumb-segments_separator']['#access'] = FALSE;
  $form['easy_breadcrumb']['easy_breadcrumb-capitalizator_ignored_words']['#access'] = FALSE;
  $form['easy_breadcrumb']['easy_breadcrumb-home_segment_title']['#states'] = array(
      'invisible' => array(
        ':input[name="easy_breadcrumb-include_home_segment"]' => array('checked' => FALSE),
  ));
}

/**
 * Implenents hook_form_FORM_ID_alter().
 */
function header_footer_form_nexteuropa_europa_search_search_form_alter(&$form, &$form_state, $form_id) {
  global $language;
  // Form element.
  $form['#attributes']['class'] = array(
    'ecl-site-header__search',
    'ecl-search-form',
  );
  $form['#attributes']['role'] = array('search');
  // Wrapper.
  $form['search_input_group']['#prefix'] = '';
  $form['search_input_group']['#suffix'] = '';
  // Textfield.
  // Flag to contextualize in HOOK_process_textfield.
  $form['search_input_group']['QueryText']['#ecl-header_footer']['header'] = TRUE;
  // Button (also managed in button.theme.inc).
  $form['search_input_group']['europa_search_submit']['#ecl-buttontype'] = 'button';
  $form['search_input_group']['europa_search_submit']['#attributes']['class'] = array(
    'ecl-button',
    'ecl-search-form__button',
    'ecl-button--search',
  );
  $search_label = module_exists('i18n_string') ? i18n_string_translate('blocks:nexteuropa_europa_search:nexteuropa_europa_search_form:title', 'Search', array('langcode' => $language->language)) : 'Search';
  $form['search_input_group']['europa_search_submit']['#value'] =
  '<span class="ecl-button__container">' .
  '<span class="ecl-button__label" data-ecl-label="true">' . $search_label . '</span>' .
  '<svg focusable="false" aria-hidden="true" data-ecl-icon="true" class="ecl-button__icon ecl-button__icon--after ecl-icon ecl-icon--xs"><use xlink:href="' . HeaderFooterHelpers::getAssetsPath() . '/images/icons/sprites/icons.svg#general--search"></use></svg>' .
  '</span></button>';
}

/**
 * Implenents hook_form_FORM_ID_alter().
 */
function header_footer_form_menu_edit_item_alter(&$form, &$form_state, $form_id) {
  // Set predefined values for the menu "Footer - Follow us".
  if ($form['parent']['#default_value'] == 'menu-footer-follow-us:0') {
    $options = array();
    foreach (HeaderFooterHelpers::getSocialMediaNetworksValues() as $name) {
      $options[$name] = $name;
    }

    $form['original_item']['#value']['options']['attributes']['class'] = array();
    $form['link_title'] = array_merge($form['link_title'], array(
      '#type' => 'select',
      '#options' => $options,
    ));
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function header_footer_form_system_themes_admin_form_alter(&$form, &$form_state, $form_id) {
  // Adding Header Footer settings.
  $fieldset_name = 'header_footer';
  $prefix = $fieldset_name . '__';
  $form[$fieldset_name] = array(
    '#type' => 'fieldset',
    '#title' => 'Header Footer',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#weight' => 5,
  );
  
  $options = array();
  foreach( array(
      'core' => array(
        'title' => 'Core',
        'img' => 'https://wikis.ec.europa.eu/download/attachments/6824781/01.%20Core%20-%20example%20-%20desktop.png?version=5&modificationDate=1571404512753&api=v2',
      ),
      'standardised' => array(
        'title' => 'Standardised',
        'img' => 'https://wikis.ec.europa.eu/download/attachments/6824798/02.%20Standardised%20-%20example%20-%20desktop.png?version=4&modificationDate=1571404444731&api=v2',
      ),
      'harmonised_group1' => array(
        'title' => 'Harmonised Group 1',
        'img' => 'https://wikis.ec.europa.eu/download/attachments/6824805/03.%20Harmonised%201%20-%20example%20-%20desktop.png?version=2&modificationDate=1571404561781&api=v2',
      ),
      'harmonised_group2' => array(
        'title' => 'Harmonised Group 2',
        'img' => 'https://wikis.ec.europa.eu/download/attachments/6824805/03.%20Harmonised%202%20-%20example%20-%20desktop.png?version=4&modificationDate=1572965104939&api=v2',
      ),'harmonised_group3' => array(
        'title' => 'Harmonised Group 3',
        'img' => '',
      ),
    )  as $value => $data){
    $options[$value] = '<img src="'.$data['img'].'" title="'.$data['title'].'"/>';
  }
    
  $field_name = $prefix . 'design';
  $form[$fieldset_name][$field_name] = array(
    '#type' => 'radios',
    '#title' => t('Design'),
    '#default_value' => variable_get($field_name, 'core'),
    '#options' => $options,
    '#description' => t('<a href="https://wikis.ec.europa.eu/display/WEBGUIDE/01.+EC+branded+websites+design" target="_blank">DGCOM</a> designs'),
  );
  
  $form = system_settings_form($form);
  if(isset($form['admin_theme']['actions'])){
    unset($form['admin_theme']['actions']);
  }
}

/**
 * Implements hook_context_load_alter().
 */
function header_footer_context_load_alter(&$context) {
  // Remove breadcrumb and footer setted by platform.
  if ($context->name === 'site_wide') {
    if (isset($context->reactions['block']['blocks']['easy_breadcrumb-easy_breadcrumb'])) {
      unset($context->reactions['block']['blocks']['easy_breadcrumb-easy_breadcrumb']);
    }

    if (isset($context->reactions['block']['blocks']['footer']) &&
    $context->reactions['block']['blocks']['footer']['delta'] == 'footer_ipg') {
      unset($context->reactions['block']['blocks']['footer']);
    }
  }
}

/**
 * Implements hook_preprocess().
 */
function header_footer_preprocess(&$variables, $hook) {
  switch ($hook) {
    case 'page':
    case 'maintenance_page':
      $variables['header_ec'] =
      $variables['footer_ec'] = '';
      if (!path_is_admin(current_path())) {
        // JS.
        drupal_add_js('https://unpkg.com/svg4everybody@2.1.9/dist/svg4everybody.js', array(
          'type' => 'external',
          'scope' => 'footer',
          'group' => JS_THEME,
        ));
        drupal_add_js(HeaderFooterHelpers::getAssetsPath('path') . '/scripts/ecl-ec-preset-legacy-website.js', array(
          'type' => 'external',
          'scope' => 'footer',
          'group' => JS_THEME,
        ));
        drupal_add_js('svg4everybody({ polyfill: true });ECL.autoInit();', array(
          'type' => 'inline',
          'scope' => 'footer',
          'group' => JS_THEME,
        ));
        // CSS.
        drupal_add_css(HeaderFooterHelpers::getAssetsPath('path') . '/styles/ecl-ec-preset-legacy-website.css',
          array(
            'type' => 'external',
        // More than CSS_THEME (=100) to not be overrided.
            'group' => 300,
            'weight' => 100,
          ));
        drupal_add_css(HeaderFooterHelpers::getAssetsPath('path') . '/styles/ecl-ec-preset-legacy-website-print.css',
          array(
            'type' => 'external',
        // More than CSS_THEME (=100) to not be overrided.
            'group' => 300,
            'weight' => 100,
            'media' => 'print',
          ));

        drupal_add_css(drupal_get_path('module', 'header_footer') . '/css/header_footer.css',
          array(
        // More than CSS_THEME (=100) to not be overrided.
            'group' => 300,
            'weight' => 101,
            'cache' => FALSE,
          ));

        // Define custom variables to be used in .tpl files.
        $variables['header_ec'] = theme('header_ec', array(
          'site_name' => $variables['site_name'],
        ));
        $variables['footer_ec'] = theme('footer_ec', array(
          'site_name' => $variables['site_name'],
        ));
      }
      else{
        drupal_add_css(drupal_get_path('module', 'header_footer') . '/css/header_footer.admin.css',
        array(
          // More than CSS_THEME (=100) to not be overrided.
            'group' => 300,
            'weight' => 101,
            'cache' => FALSE,
          ));
      }
      break;
  }

  // Suggest templates according website design setting.
  switch($hook){
    case 'footer_ec':
    case 'header_ec':
      $variables['theme_hook_suggestions'][] = $hook . '__header_footer_' . variable_get('header_footer__design', 'core');
      break;
  }
}